[package]
name = "trex"
version = "0.1.0"
edition = "2021"
description = "Transmission Rating Explorer (TREX) WebAssembly & Python Library"

[lib]
name = "trex"
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = { version = "0.2.126", optional = true }
pyo3 = { version = "0.22.6", features = ["extension-module"], optional = true }

[features]
default = ["wasm"]
wasm = ["dep:wasm-bindgen"]
python = ["dep:pyo3"]

[profile.release]
opt-level = "s"
lto = true
